2021-06-25 15:42:01|INFO|gpload session started 2021-06-25 15:42:01
2021-06-25 15:42:01|INFO|setting schema 'public' for table 'testspecialchar'
2021-06-25 15:42:01|INFO|started gpfdist -p 8081 -P 8082 -f "pathto/data_file.txt" -t 30
2021-06-25 15:42:01|INFO|did not find an external table to reuse. creating ext_gpload_reusable_d3fc4012_d588_11eb_9eaa_0050569e5d5e
2021-06-25 15:42:01|ERROR|could not run SQL "create external table ext_gpload_reusable_d3fc4012_d588_11eb_9eaa_0050569e5d5e("Field1" bigint,"Field#2" text)location('gpfdist://*:pathto/data_file.txt') format 'text' (delimiter ';' null '\N' escape '\') encoding'UTF8' ": ERROR:  syntax error at or near "UTF8"
LINE 1: ... 'text' (delimiter ';' null '\N' escape '\') encoding'UTF8' 
                                                                 ^

2021-06-25 15:42:01|INFO|rows Inserted          = 0
2021-06-25 15:42:01|INFO|rows Updated           = 0
2021-06-25 15:42:01|INFO|data formatting errors = 0
2021-06-25 15:42:01|INFO|gpload failed
2021-06-25 15:42:01|INFO|gpload session started 2021-06-25 15:42:01
2021-06-25 15:42:01|INFO|setting schema 'public' for table 'testspecialchar'
2021-06-25 15:42:01|INFO|started gpfdist -p 8081 -P 8082 -f "pathto/data_file.txt" -t 30
2021-06-25 15:42:01|INFO|did not find an external table to reuse. creating ext_gpload_reusable_d4109c56_d588_11eb_af2e_0050569e5d5e
2021-06-25 15:42:01|ERROR|could not run SQL "create external table ext_gpload_reusable_d4109c56_d588_11eb_af2e_0050569e5d5e("Field1" bigint,"Field#2" text)location('gpfdist://*:pathto/data_file.txt') format 'text' (delimiter ';' null '\N' escape '\') encoding'UTF8' ": ERROR:  syntax error at or near "UTF8"
LINE 1: ... 'text' (delimiter ';' null '\N' escape '\') encoding'UTF8' 
                                                                 ^

2021-06-25 15:42:01|INFO|rows Inserted          = 0
2021-06-25 15:42:01|INFO|rows Updated           = 0
2021-06-25 15:42:01|INFO|data formatting errors = 0
2021-06-25 15:42:01|INFO|gpload failed
2021-06-25 15:42:01|INFO|gpload session started 2021-06-25 15:42:01
2021-06-25 15:42:01|INFO|setting schema 'public' for table 'testspecialchar'
2021-06-25 15:42:01|INFO|started gpfdist -p 8081 -P 8082 -f "pathto/data_file2.txt" -t 30
2021-06-25 15:42:01|INFO|did not find a staging table to reuse. creating staging_gpload_reusable_a1101b5024707ea34f55e778f329e548
2021-06-25 15:42:01|INFO|did not find an external table to reuse. creating ext_gpload_reusable_d424d5e0_d588_11eb_8503_0050569e5d5e
2021-06-25 15:42:01|ERROR|could not run SQL "create external table ext_gpload_reusable_d424d5e0_d588_11eb_8503_0050569e5d5e("Field1" bigint,"Field#2" text)location('gpfdist://*:pathto/data_file2.txt') format 'text' (delimiter ';' null '\N' escape '\') encoding'UTF8' ": ERROR:  syntax error at or near "UTF8"
LINE 1: ... 'text' (delimiter ';' null '\N' escape '\') encoding'UTF8' 
                                                                 ^

2021-06-25 15:42:01|INFO|rows Inserted          = 0
2021-06-25 15:42:01|INFO|rows Updated           = 0
2021-06-25 15:42:01|INFO|data formatting errors = 0
2021-06-25 15:42:01|INFO|gpload failed
2021-06-25 15:42:01|INFO|gpload session started 2021-06-25 15:42:01
2021-06-25 15:42:01|INFO|setting schema 'public' for table 'testspecialchar'
2021-06-25 15:42:01|ERROR|no mapping for input column "'Field1'" to output table
2021-06-25 15:42:01|INFO|rows Inserted          = 0
2021-06-25 15:42:01|INFO|rows Updated           = 0
2021-06-25 15:42:01|INFO|data formatting errors = 0
2021-06-25 15:42:01|INFO|gpload failed
2021-06-25 15:42:01|INFO|gpload session started 2021-06-25 15:42:01
2021-06-25 15:42:01|INFO|setting schema 'public' for table 'testspecialchar'
2021-06-25 15:42:01|INFO|started gpfdist -p 8081 -P 8082 -f "pathto/data_file2.txt" -t 30
2021-06-25 15:42:01|INFO|did not find a staging table to reuse. creating staging_gpload_reusable_a1101b5024707ea34f55e778f329e548
2021-06-25 15:42:01|INFO|did not find an external table to reuse. creating ext_gpload_reusable_d44d2ba8_d588_11eb_a2a1_0050569e5d5e
2021-06-25 15:42:01|ERROR|could not run SQL "create external table ext_gpload_reusable_d44d2ba8_d588_11eb_a2a1_0050569e5d5e("Field1" bigint,"Field#2" text)location('gpfdist://*:pathto/data_file2.txt') format 'text' (delimiter ';' null '\N' escape '\') encoding'UTF8' ": ERROR:  syntax error at or near "UTF8"
LINE 1: ... 'text' (delimiter ';' null '\N' escape '\') encoding'UTF8' 
                                                                 ^

2021-06-25 15:42:01|INFO|rows Inserted          = 0
2021-06-25 15:42:01|INFO|rows Updated           = 0
2021-06-25 15:42:01|INFO|data formatting errors = 0
2021-06-25 15:42:01|INFO|gpload failed
