2021-01-07 07:27:52|INFO|gpload session started 2021-01-07 07:27:52
2021-01-07 07:27:52|INFO|setting schema 'public' for table 'testspecialchar'
2021-01-07 07:27:52|INFO|started gpfdist -p 8081 -P 8082 -f "pathto/data_file.txt" -t 30
2021-01-07 07:27:52|INFO|did not find an external table to reuse. creating ext_gpload_reusable_d9f87890_50b9_11eb_97d4_0242ac120005
2021-01-07 07:27:52|ERROR|could not run SQL "create external table ext_gpload_reusable_d9f87890_50b9_11eb_97d4_0242ac120005("Field1" bigint,"Field#2" text)location('gpfdist://*:pathto/data_file.txt') format 'text' (delimiter ';' null '\N' escape '\') encoding'UTF8' ": ERROR:  syntax error at or near "UTF8"
LINE 1: ... 'text' (delimiter ';' null '\N' escape '\') encoding'UTF8' 
                                                                 ^

2021-01-07 07:27:52|INFO|rows Inserted          = 0
2021-01-07 07:27:52|INFO|rows Updated           = 0
2021-01-07 07:27:52|INFO|data formatting errors = 0
2021-01-07 07:27:52|INFO|gpload failed
2021-01-07 07:27:52|INFO|gpload session started 2021-01-07 07:27:52
2021-01-07 07:27:52|INFO|setting schema 'public' for table 'testspecialchar'
2021-01-07 07:27:52|INFO|started gpfdist -p 8081 -P 8082 -f "pathto/data_file.txt" -t 30
2021-01-07 07:27:52|INFO|did not find an external table to reuse. creating ext_gpload_reusable_da410e34_50b9_11eb_b64d_0242ac120005
2021-01-07 07:27:52|ERROR|could not run SQL "create external table ext_gpload_reusable_da410e34_50b9_11eb_b64d_0242ac120005("Field1" bigint,"Field#2" text)location('gpfdist://*:pathto/data_file.txt') format 'text' (delimiter ';' null '\N' escape '\') encoding'UTF8' ": ERROR:  syntax error at or near "UTF8"
LINE 1: ... 'text' (delimiter ';' null '\N' escape '\') encoding'UTF8' 
                                                                 ^

2021-01-07 07:27:52|INFO|rows Inserted          = 0
2021-01-07 07:27:52|INFO|rows Updated           = 0
2021-01-07 07:27:52|INFO|data formatting errors = 0
2021-01-07 07:27:52|INFO|gpload failed
2021-01-07 07:27:53|INFO|gpload session started 2021-01-07 07:27:53
2021-01-07 07:27:53|INFO|setting schema 'public' for table 'testspecialchar'
2021-01-07 07:27:53|INFO|started gpfdist -p 8081 -P 8082 -f "pathto/data_file2.txt" -t 30
2021-01-07 07:27:53|INFO|did not find a staging table to reuse. creating staging_gpload_reusable_a1101b5024707ea34f55e778f329e548
2021-01-07 07:27:53|INFO|did not find an external table to reuse. creating ext_gpload_reusable_da82af6a_50b9_11eb_a7cb_0242ac120005
2021-01-07 07:27:53|ERROR|could not run SQL "create external table ext_gpload_reusable_da82af6a_50b9_11eb_a7cb_0242ac120005("Field1" bigint,"Field#2" text)location('gpfdist://*:pathto/data_file2.txt') format 'text' (delimiter ';' null '\N' escape '\') encoding'UTF8' ": ERROR:  syntax error at or near "UTF8"
LINE 1: ... 'text' (delimiter ';' null '\N' escape '\') encoding'UTF8' 
                                                                 ^

2021-01-07 07:27:53|INFO|rows Inserted          = 0
2021-01-07 07:27:53|INFO|rows Updated           = 0
2021-01-07 07:27:53|INFO|data formatting errors = 0
2021-01-07 07:27:53|INFO|gpload failed
2021-01-07 07:27:53|INFO|gpload session started 2021-01-07 07:27:53
2021-01-07 07:27:53|INFO|setting schema 'public' for table 'testspecialchar'
2021-01-07 07:27:53|ERROR|no mapping for input column "'Field1'" to output table
2021-01-07 07:27:53|INFO|rows Inserted          = 0
2021-01-07 07:27:53|INFO|rows Updated           = 0
2021-01-07 07:27:53|INFO|data formatting errors = 0
2021-01-07 07:27:53|INFO|gpload failed
2021-01-07 07:27:53|INFO|gpload session started 2021-01-07 07:27:53
2021-01-07 07:27:53|INFO|setting schema 'public' for table 'testspecialchar'
2021-01-07 07:27:54|ERROR|no mapping for input column "Field1" to output table
2021-01-07 07:27:54|INFO|rows Inserted          = 0
2021-01-07 07:27:54|INFO|rows Updated           = 0
2021-01-07 07:27:54|INFO|data formatting errors = 0
2021-01-07 07:27:54|INFO|gpload failed
